### PR TITLE
test: use kaocha test-runner for cljs

### LINKED ISSUE #89: Resolve reported vulnerabilities
See https://github.com/replikativ/konserve/security/dependabot

### PR DESCRIPTION
**Pull request by jsmassa**
We are already using kaocha for our clojure tests, so it simplifies things if we are moving to kaocha for clojurescript as well.

Fixes #89.

### CODE REVIEW

**Comment by jsmassa** [comment]
Unfortunately kaocha's node test runner fails for this project with an error after all tests have been executed. Until the problem has been fixed I am using the [olical cljs test runner](https://github.com/Olical/cljs-test-runner) here, which also requires only a setup in the deps.edn and no further config or runner files.

We can also try simply updating the karma packages. Vulnerabilities still shown on my system might be just a local problem.

**Comment by TimoKramer** [comment]
Does not work right now because of #96

**Comment by jsmassa** [comment]
The problem is fixed now with support for salt as in the clojure version still missing as stated in [this comment](https://github.com/replikativ/konserve/blob/9857ad91306a40bfaf4300c35ce87b57d9dbc884/src/konserve/encryptor.cljc#L28).

**Review by TimoKramer — DISMISSED** [review]

**Comment by TimoKramer** [comment]
Just uncomment the cljstest from main and it should be working

**Review by whilo — APPROVED** [review]

**Comment by whilo** [comment]
You can either merge now or wait for my cljs fix in the next days.

**Comment by jsmassa** [comment]
A couple more days won't make much of a difference I guess.

**Comment by whilo** [comment]
This now implements the corresponding salt concatenation in ClojureScript, but I am certain that the cljs tests are not properly executed. Can you check that you can really execute the tests and then we need to figure out why the cljstest here passed earlier while the unit test correctly failed in https://circleci.com/gh/replikativ/konserve/788 ? On my machine I get macro import compile errors (which also might be my setup) and cannot run the tests or start a REPL atm.

**Comment by jsmassa** [comment]
Is there still a problem? Like on the server, all of the tests are passing on my system. 

I get a few warnings, but cleanups of this repo will be the goal of PR #88.

**Comment by jsmassa** [comment]
Fixed  the lz4 warning though as this is a seems to be a difference in cljs

**Comment by jsmassa** [comment]
What about the line [here](https://github.com/replikativ/konserve/blob/e2c1cb45708006a62a1df2133261620a2b70c3c8/src/konserve/compressor.cljc#L57)? Isn't that supposed to be the unsupported compressor as well in case of an exception in the clojure code?

**Comment by whilo** [comment]
AES is now fixed in cljs and has the same cold storage format as in Clojure (i.e. you can read the same store from Clojure and ClojureScript), thanks to the help of @pkpkpk :tada: . A problem was that the cljs compliance test was not run asynchronously and I think this is why it just passed before it failed.

**Comment by whilo** [comment]
> What about the line [here](https://github.com/replikativ/konserve/blob/e2c1cb45708006a62a1df2133261620a2b70c3c8/src/konserve/compressor.cljc#L57)? Isn't that supposed to be the unsupported compressor as well in case of an exception in the clojure code?

@jsmassa I think this try-catch can be removed (it is redundant), it accidentally slipped in there while I was getting the native build to work.

**Pull request merged**
