### PR TITLE
assoc-in should update nested value

### LINKED ISSUE #120: assoc-in bug
[this](https://github.com/replikativ/konserve/blob/1875076715418bac78b9e70cdb31631282e85615/src/konserve/impl/defaults.cljc#L363) should update nested paths instead of overwriting root value.

Expected behavior should be more akin to:

```clj
(defn assoc-in
  [store key-vec val opts]
  (let [[path-vec key] ((juxt pop peek) key-vec)]
    (k/update-in store path-vec #(clojure.core/assoc % key val) opts)))
```

Simple fix but given its duration should be grouped into a breaking-change release

### PR DESCRIPTION
**Pull request by whilo**
Fix #120.

### CODE REVIEW

**Comment by whilo** [comment]
@pkpkpk I decided to fix it internally in `-assoc-in` as this avoids the read operation for `assoc` when the old value is not needed.

**Comment by pkpkpk** [comment]
you dont want to change the PEDNKeyValueStore impl?

**Comment by whilo** [comment]
I have changed it, it is now not overwriting the value in case `assoc-in` only operates on a nested value. The bug was introduced to avoid reading the old value when you call `assoc`, but introduced the bug for `assoc-in` where the old value was ignored and only the new one was `assoc`ed.

**Review by pkpkpk — APPROVED** [review]
lgtm

**Pull request merged**
