### PR TITLE
cljs fixes

### PR DESCRIPTION
**Pull request by pkpkpk**

### CODE REVIEW

**Comment by whilo** [comment]
@pkpkpk This looks good to me. Lmk when you want to have it merged. Also, are these changes covered by CI/CD tests for cljs?

**Comment by pkpkpk** [comment]
I want to cut a fress release to silence some warnings and then tweak the tests here to run on advanced builds, do a little more in the browser tests.

@whilo Ill make those changes and then ping you on slack to help get CI running

**Comment by pkpkpk** [comment]
### In Summary

1) fixes macro referencing ambiguity in cljs
2) Decoupled tests from the store being tested. Tests are now `function<store>` organized by namespaces that test a particular aspect. These namespaces are in `test/konserve/tests` and can be used by 3rd party implementers as an addendum to the compliance test. The migration test was left as is.
3) Each store runs the same tests (but no sync/CBOR for cljs) . This is a modest increase in coverage for the jvm filestore but a huge gain for cljs and was critical for increasing behavior parity. This closes #93 
4) I brain dumped usage details into [docs/api-walkthrough.md](https://github.com/pkpkpk/konserve/blob/main/doc/api-walkthrough.md), hopefully this addresses the ambiguity discussed in #109 and #71
5) update some deps, pruning of old config, & assortment of random fixes, closes #108 
6) `bin/run-all` will run the jvm filestore test and the tests for both indexeddb and nodejs with advanced optimizations, and will log and exit non-zero on failure

```bash
./bin/install
./bin/run-all
```

#### future work
1) changes to enable record safety path in advanced builds
2) compression tests, LZ4 cljs support
3) CBOR cljs support, handler documentation
4) cljs benchmarks

**Comment by whilo** [comment]
That sounds good. Is this ready for review/merging? @pkpkpk

**Comment by pkpkpk** [comment]
Yes I think it's in a good place. Will revisit record handling safety in cljs another time

**Review by whilo — APPROVED** [review]
It looks solid overall. Thank you so much for turning the cljs support robust! I will merge this now to test the CI. We should also update the README to point to your implementation notes, or better, merge them. So maybe a follow up PR will be necessary.

**Pull request merged**
